### ISSUE TITLE
Debugging the director  (not found) error when gathering resources during the `bookinder bind local

### ISSUE THREAD

**Issue by timani** [timani/bookbinder#2]
Debugging the director  (not found) error when gathering resources during the `bookinder bind local` command 

```
tmunyaradzi:pcf-onboarding tmunyaradzi$ bundle exec bookbinder bind local
  copying /Users/tmunyaradzi/Pivotal/GSS/pcf-book-onboarding/docs-layout-repo
Gathering cloud-foundry-fundamentals
  skipping (not found) /Users/tmunyaradzi/Pivotal/GSS/pcf-book-onboarding/cloud-foundry-fundamentals

Checking for broken links...
/search.html => /logsearch/index.html
/search.html => /logsearch/installing.html
/search.html => /logsearch/scaling.html
/search.html => /logsearch/using.html
/search.html => /logsearch/search-guide.html
/search.html => /logsearch/release.html

Found 6 broken links!
Bookbinder bound your book into /Users/tmunyaradzi/Pivotal/GSS/pcf-book-onboarding/pcf-onboarding/final_app

tmunyaradzi:pcf-onboarding tmunyaradzi$ bundle exec bookbinder bind local
  copying /Users/tmunyaradzi/Pivotal/GSS/pcf-book-onboarding/docs-layout-repo
Gathering cf-fundamentals
  copying /Users/tmunyaradzi/Pivotal/GSS/pcf-book-onboarding/cf-fundamentals

```

Make sure the name of the repository in the section matches the names of the sibling directory:

```

---
book_repo: '.'
public_host: ''
feedback_enabled: false
layout_repo: docs-layout-repo

sections:
- repository:
    name: cf-fundamentals
  directory: cf-fundamentals
  subnav_template: pivotal_logsearch_subnav.erb
```

Ensure that the directory exists within the same project directory on the same level as the main bookbinder directory, in this case the `cf-fundamentals` section maps to a directory on the same level as the `pcf-onboarding` directory. 

```
tmunyaradzi:pcf-book-onboarding tmunyaradzi$ ls -l
total 24
-rw-r--r--   1 tmunyaradzi  staff    49 Jun 29 21:27 Gemfile
-rw-r--r--   1 tmunyaradzi  staff  4789 Jun 29 21:27 Gemfile.lock
drwxr-xr-x  14 tmunyaradzi  staff   476 Jun 29 21:43 cf-fundamentals
drwxr-xr-x   7 tmunyaradzi  staff   238 Jun 29 21:46 docs-layout-repo
drwxr-xr-x  10 tmunyaradzi  staff   340 Jul  4 22:30 pcf-onboarding
```
